# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            artoo
tagline:          'The client-side scraping companion.'
description:      'The client-side scraping companion.'
baseurl:          '/artoo'

author:
  name:           'Yomguithereal'
  url:            https://github.com/Yomguithereal

# Custom vars
version:          0.0.2

sidebar:
  - url: 'quick_start'
    title: 'Quick Start'
  - 'sep'
  - url: 'methods'
    title: 'Methods'
    children:
      - url: 'helpers'
        title: 'Helpers'
      - url: 'instructions'
        title: 'Instructions'
  - url: 'settings'
    title: 'Settings'
  - url: 'grunt'
    title: 'Grunt'
  - 'sep'

github:
  repo:           https://github.com/medialab/artoo

medialab:
  url:            'http://www.medialab.sciences-po.fr/'

bookmarklet:      'javascript: (function(){var t={},e=!0;if("object"==typeof this.artoo)artoo.reload||(artoo.log.verbose("artoo already lies within this page. No need to inject him again."),artoo.loadSettings(t),artoo.hooks.trigger("exec"),e=!1);else if(e){var o=document.getElementsByTagName("body")[0],a=document.createElement("script");console.log("artoo is loading..."),a.src="https://raw.githubusercontent.com/medialab/artoo/master/build/artoo.min.js",a.type="text/javascript",a.id="artoo_injected_script",a.setAttribute("settings",JSON.stringify(t)),o.appendChild(a)}}).call(this);'
