# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            artoo
tagline:          'The client-side scraping companion.'
description:      'The client-side scraping companion.'
baseurl:          '/artoo'

author:
  name:           'Yomguithereal'
  url:            https://github.com/Yomguithereal

# Custom vars
version:          0.0.2

sidebar:
  - url: 'quick_start'
    title: 'Quick Start'
  - url: 'hacker_news'
    title: 'Hacker News scraper'
  - 'sep'
  - url: 'methods'
    title: 'Methods'
    children:
      - url: 'expand'
        title: 'Autoexpand'
      - url: 'helpers'
        title: 'Helpers'
      - url: 'instructions'
        title: 'Instructions'
      - url: 'save'
        title: 'Save'
      - url: 'scrape'
        title: 'Scrape'
      - url: 'spiders'
        title: 'Spiders'
      - url: 'store'
        title: 'Store'
  - url: 'settings'
    title: 'Settings'
  - url: 'jquery'
    title: 'jQuery injection'
  - url: 'chrome'
    title: 'Chrome extension'
  - url: 'grunt'
    title: 'Grunt task'
  - 'sep'

github:
  repo:           https://github.com/medialab/artoo

medialab:
  url:            'http://www.medialab.sciences-po.fr/'

bookmarklets:      
  artoo:          'javascript: (function(){var t={},o=!0;if("object"==typeof this.artoo)artoo.reload||(artoo.log.verbose("artoo already lies within this page. No need to inject him again."),artoo.loadSettings(t),artoo.hooks.trigger("exec"),o=!1);else if(o){var e=document.getElementsByTagName("body")[0],i=document.createElement("script");console.log("artoo is loading..."),i.src="//medialab.github.io/artoo/public/js/artoo.min.js",i.type="text/javascript",i.id="artoo_injected_script",i.setAttribute("settings",JSON.stringify(t)),e.appendChild(i)}}).call(this);'
  hackernews:     >
    'javascript: (function(){var t={eval:'"(function(){function t(t){return artoo.scrape(t.find(\\"tr tr:has(td.title:has(a)):not(:last)\\"),{title:{sel:\\".title a\\"},url:{sel:\\".title a\\",attr:\\"href\\"},domain:{sel:\\".comhead\\",method:function(t){return t(this).text().trim().replace(/[\\\\(\\\\)]/g,\\"\\")}},score:{sel:\\"+ tr [id^=score]\\",method:function(t){return+t(this).text().replace(/ points/,\\"\\")}},user:{sel:\\"+ tr a[href^=user]\\",method:function(t){return t(this).length?t(this).text():null}},nb_comments:{sel:\\"+ tr a[href^=item]\\",method:function(t){var e=+t(this).text().replace(/ comments/,\\"\\");return isNaN(e)?0:e}}})}function e(t){return t.find(\\"td.title:last > a\\").attr(\\"href\\")}artoo.log.debug(\\"Starting the scraper...\\");var r=t(artoo.$(document));artoo.ajaxSpider(function(t,r){return e(t?artoo.$(r):artoo.$(document))},{limit:2,callback:function(e,r){return artoo.log.debug(\\"Fecthed page \\"+(r+1)),t(artoo.$(e))},concat:!0,done:function(t){artoo.log.debug(\\"Finished retrieving data. Downloading...\\"),artoo.savePrettyJson(r.concat(t),{filename:\\"hacker_news.json\\"})}})}).call(this);"'},e=!0;if("object"==typeof this.artoo)artoo.reload||(artoo.log.verbose("artoo already lies within this page. No need to inject him again."),artoo.loadSettings(t),artoo.hooks.trigger("exec"),e=!1);else if(e){var o=document.getElementsByTagName("body")[0],r=document.createElement("script");console.log("artoo is loading..."),r.src="//medialab.github.io/artoo/public/js/artoo.min.js",r.type="text/javascript",r.id="artoo_injected_script",r.setAttribute("settings",JSON.stringify(t)),o.appendChild(r)}}).call(this);'
