# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            artoo
tagline:          'The client-side scraping companion.'
description:      'The client-side scraping companion.'
baseurl:          '/artoo'

author:
  name:           'Yomguithereal'
  url:            https://github.com/Yomguithereal

# Custom vars
version:          0.0.2

sidebar:
  - url: 'quick_start'
    title: 'Quick Start'
  - 'sep'
  - url: 'methods'
    title: 'Methods'
    children:
      - url: 'expand'
        title: 'Autoexpand'
      - url: 'helpers'
        title: 'Helpers'
      - url: 'instructions'
        title: 'Instructions'
      - url: 'save'
        title: 'Save'
      - url: 'scrape'
        title: 'Scrape'
      - url: 'spiders'
        title: 'Spiders'
      - url: 'store'
        title: 'Store'
  - url: 'settings'
    title: 'Settings'
  - url: 'jquery'
    title: 'jQuery injection'
  # - url: 'chrome'
  #   title: 'Chrome extension'
  - url: 'grunt'
    title: 'Grunt'
  - 'sep'

github:
  repo:           https://github.com/medialab/artoo

medialab:
  url:            'http://www.medialab.sciences-po.fr/'

bookmarklets:      
  artoo:          'javascript: (function(){var t={},o=!0;if("object"==typeof this.artoo)artoo.reload||(artoo.log.verbose("artoo already lies within this page. No need to inject him again."),artoo.loadSettings(t),artoo.hooks.trigger("exec"),o=!1);else if(o){var e=document.getElementsByTagName("body")[0],i=document.createElement("script");console.log("artoo is loading..."),i.src="//medialab.github.io/artoo/public/js/artoo.min.js",i.type="text/javascript",i.id="artoo_injected_script",i.setAttribute("settings",JSON.stringify(t)),e.appendChild(i)}}).call(this);'
  hackernews:     ''
